FROM n8nio/n8n:latest

ENV GENERIC_TIMEZONE=Asia/Jakarta
ENV N8N_PORT=5678
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=password123
ENV NODE_ENV=production
ENV N8N_HOST=0.0.0.0
ENV WEBHOOK_TUNNEL_URL=https://n8n-2-1h9c.onrender.com
ENV N8N_USER_FOLDER=/home/node/.n8n

EXPOSE 5678

